
# 주석처리되어있는 학교는 인코딩 및 공지사항 화면을 불러올 수 없을 경우
__all__ = ['snu',
           'yonsei',
           'korea',
           'sugang',
           'sungkyun',
           #'hanyang',
           'jungang',
           #'kyounghee',
           'hufs',
           'uos',
           'ewha',
           'konkuk',
           'dongguk',
            'hongik',
           'gandong',
           'gunyang',
           # 'kyoungbuk',
           'kyoungsang',
           # 'donga',
           'busan',
           'yonsei_wonju',
           'injae',
           'junnam',
           'junbuk',
           'josun',
           'chungnam',
           'chungbuk',
           'gachown',
           'gatolic',
           'danguk',
           'youngnam',
           'ulsan',
           'wongang',
           'eulji',
           'hanlim',
           'gangleungwonju',
           'gaemyoung',
           'seonam',
           'sounchown',
           'aju',
           'inha',
           ]
